[tool.poetry]
name = "litestar-crud"
version = "0.1.0"
description = ""
authors = ["Sergei Firsov <sergey.firsov@aisa.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
