version: "3.9"

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: litestar
    networks:
      litestar:
    volumes:
      - pg_data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=64MB"
      - "-c"
      - "effective_cache_size=512MB"
      - "-c"
      - "log_min_duration_statement=500"
    ports:
      - "5432:5432"

  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: litestar_api
    working_dir: /app
    networks:
      litestar:
    environment:
      PG_HOST: localhost
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DATABASE: litestar
    ports:
      - "8000:8000"
    depends_on:
      - postgres

networks:
  litestar:
    name: litestar
    driver: bridge

volumes:
  pg_data:
